docker-compose-yaml: docker-compose.yml

environments:
  production:
    deploy: true
    env:
      LAGOON_ENVIRONMENT_TYPE: production

  development:
    deploy: true
    env:
      LAGOON_ENVIRONMENT_TYPE: development
