docker-compose-yaml: docker-compose.yml

environment_variables:
  git_sha: 'true'

tasks:
  pre-rollout:
    - run:
        name: drush sql-dump
        command: echo "this is Neil's pre-rollout"
        service: cli
	shell: bash
  post-rollout:
    - run:
        name: drush cim
        command: echo "this is Neil's post-rollout"
        service: cli
        shell: bash

