apiVersion: v1
kind: Pod
metadata:
  labels:
    run: metamirror
  name: metamirror
spec:
  serviceAccountName: metamirror-operator
  containers:
  - image: neilharris123/metamirror:v0.0.1
    imagePullPolicy: Always
    name: metamirror
    env:
    - name: MM_ANNOTATION
      value: "example/annotation"
    - name:  MM_LABEL
      value: "examplelabel"
